# Generated by Django 5.2.1 on 2025-05-15 20:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_tiposobretiempo_sobretiempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobretiempo',
            name='numero_horas',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
